# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ec2-precise64"
  config.vm.box_url =
    "https://s3.amazonaws.com/mediacore-public/boxes/ec2-precise64.box"
  config.vm.provision :shell do |shell|
    shell.path = ENV['PLOY_BUILD_SCRIPT']
    shell.args = "/build /build/.ploy/cache /build/.ploy/slugs/#{ENV['PLOY_RELEASE_ID']}"
  end
  config.vm.synced_folder ENV['PLOY_APP_ROOT'], "/build"
  config.ssh.forward_agent = true
end
