# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "precise-server-cloudimg"
  config.vm.box_url =
    "https://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.provision :shell do |shell|
    shell.path = ENV['PLOY_BUILD_SCRIPT']
    shell.args = "/build /tmp/build-cache /build/.release/#{Time.now.to_i}"
  end
  config.vm.synced_folder ENV['PLOY_APP_ROOT'], "/build"
  config.ssh.forward_agent = true
end
