#!/bin/sh

set -e

fail() {
  echo $@ >&2
  exit 1
}

SOURCE_DIR=$1
CACHE_DIR=$2
DESTDIR=$3
RELEASE_ID=`basename "$DESTDIR"`

export XDG_CACHE_HOME=$CACHE_DIR

echo "Preparing to build release '$RELEASE_ID'"

if [ ! -x "$SOURCE_DIR/script/slugify" ]; then
  fail "We're missing a script/slugify script in the source"
fi

if ! "$SOURCE_DIR/script/slugify" "$CACHE_DIR" "$DESTDIR" ; then
  fail "Build failure (see logs)"
fi

if [ ! -x "$DESTDIR/script/install" ] ; then
  fail "We're missing a script/install script in the slug"
fi

cd "$DESTDIR"
if ! tar czf "../$RELEASE_ID.tar.gz" . ; then
  fail "Archive creating issue ??"
fi

echo "Build of release '$RELEASE_ID' successful"
